### ISSUE TITLE
Denom unit for price / denom is showing minting denom instead of the display denom

### ISSUE THREAD

**Issue by kwunyeung** [forbole/big-dipper#286]
`this.state.mint` here is always `null` as it has not been set in anywhere.

https://github.com/forbole/big-dipper/blob/ddc8c8d982cd6d6c32b615bffefc0c6c9a239e15/imports/ui/accounts/Account.jsx#L246

**Comment by MonikaCat** [comment]
Fixed in PR #287

**Comment by kwunyeung** [comment]
@MonikaCat I'm using the latest master but it's still showing the mint denom.
![image](https://user-images.githubusercontent.com/932636/74929316-34331c80-5416-11ea-8931-6ac271ed26d0.png)

**Comment by MonikaCat** [comment]
That's strange because when I run the master it displays it correctly with the Staking Denom  

![image](https://user-images.githubusercontent.com/37407870/74999138-bb73a500-5495-11ea-882d-cc37247558a9.png)
Could you please confirm that your code  https://github.com/forbole/big-dipper/blob/master/imports/ui/accounts/Account.jsx#L337 is reading the Denom value from the Coin utility as shown below? 
`({numbro(this.state.price).format("$0,0.00")}/{Coin.StakingCoin.displayName})`

**Comment by kwunyeung** [comment]
I see. This is fixed in the latest PR #287 .
